### ISSUE TITLE
Doesn't work in Intelij Idea

### ISSUE THREAD

**Issue by flaghacker** [miquelbeltran/kotlin-code-gen-sample#3]
I'm trying to get this example working, and it does if I manually run `gradlew build`. It doesn't work in Idea though, I need to manually run gradle every time after making changes to the generator or to the before-generation files.

It works if I delegate build/run actions to gradle, but things still don't automatically update in the IDE. Is there any solution to this?

**Comment by miquelbeltran** [comment]
I think you have a configuration problem on your Intelij project configuration.

Did you go through this import process?

![screenshot 2018-10-18 at 15 26 10](https://user-images.githubusercontent.com/2494376/47158938-05220d80-d2ed-11e8-9b18-57294b3410dc.png)

A common problem cause is the lack of a configured JDK

![screenshot 2018-10-18 at 15 47 06](https://user-images.githubusercontent.com/2494376/47158991-1f5beb80-d2ed-11e8-80a0-3da52faf8434.png)

Once you fix it and reimport the project, you will be able to run the gradle tasks from inside IntelliJ

![screenshot 2018-10-18 at 15 45 51](https://user-images.githubusercontent.com/2494376/47159020-313d8e80-d2ed-11e8-9dd7-633bea84cd5c.png)
